blanks = [98, 112, 126, 140, 154, 168, 182, 1, 29, 43, 57, 71, 85, 99, 113, 141, 169, 183, 2, 30, 58, 3, 31, 59, 73, 101, 115, 143, 171, 185, 4, 32, 60, 74, 102, 116, 144, 172, 186, 5, 33, 61, 75, 103, 117, 145, 173, 187, 104, 118, 146, 174, 188, 7, 35, 63, 77, 105, 119, 147, 175, 189, 8, 36, 64, 78, 106, 120, 148, 176, 190, 9, 37, 65, 10, 24, 38, 66, 80, 108, 122, 150, 164, 178, 192, 11, 25, 39, 67, 81, 109, 123, 137, 151, 165, 179, 193, 12, 26, 166, 180, 194, 13, 27, 41, 69, 83, 111, 125, 139, 153, 167, 181, 195]
size = 14

[across]
INTEGRINS = [155, "Cell surface receptors that anchor cells to the extracellular matrix and relay mechanical signals inside."]
ANGIOGENESIS = [44, "Formation of new blood vessels that feed tumors and support their growth and spread."]
ALLOSTASIS = [127, "The process of achieving stability through physiological or behavioral changes in response to stress."]
INFLAMMATION = [86, "A bodily response to infection or injury, often causing redness and swelling."]
ASTROCYTES = [14, "Star-shaped support cells in the brain that nourish neurons, maintain homeostasis, and turn harmful when reactive in disease."]

[down]
MICROGLIA = [40, "Brain’s resident immune cells that protect neurons but can drive chronic inflammation in disease."]
HYPOXIA = [6, "Low oxygen zones inside tumors that trigger survival, angiogenesis, and therapy resistance."]
MALARIA = [0, "Infectious, misfolded protein that causes healthy proteins to misfold, leading to fatal neurodegenerative diseases"]
VIRULENCE = [72, "The degree of pathogenicity or ability of a microbe to cause disease."]
PARKINSON = [79, "A neurodegenerative disorder marked by tremors and dopamine depletion."]
